In [ ]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [2]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    data['text'], data['label'], 
    test_size=0.2, random_state=42, stratify=data['label'])

## Data Preprocessing

In [4]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\alber\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [5]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [6]:
import re

X_train = X_train.str.replace(r"(?is)<(script|style).*?>.*?(</\1>)", "", regex=True)
X_train = X_train.str.replace(r"(?s)<!--(.*?)-->[\n]?", "", regex=True)
X_train = X_train.str.replace(r"(?s)<.*?>", " ", regex=True)

X_test = X_test.str.replace(r"(?is)<(script|style).*?>.*?(</\1>)", "", regex=True)
X_test = X_test.str.replace(r"(?s)<!--(.*?)-->[\n]?", "", regex=True)
X_test = X_test.str.replace(r"(?s)<.*?>", " ", regex=True)

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [7]:

#Remove all special characters
X_train = X_train.str.replace(r'\W', ' ', regex=True)
X_test = X_test.str.replace(r'\W', ' ', regex=True)

#Remove numbers
X_train = X_train.str.replace(r'\d+', ' ', regex=True)
X_test= X_test.str.replace(r'\d+', ' ', regex=True)

#Remove all single characters
X_train = X_train.str.replace(r'\s+[a-zA-Z]\s+', ' ', regex=True)
X_test= X_test.str.replace(r'\s+[a-zA-Z]\s+', ' ', regex=True)

#Remove single characters from the start
X_train = X_train.str.replace(r'^[a-zA-Z]\s+', ' ', regex=True)
X_test= X_test.str.replace(r'^[a-zA-Z]\s+', ' ', regex=True)

#Substitute multiple spaces with single space
X_train = X_train.str.replace(r'\s+', ' ', regex=True)
X_test= X_test.str.replace(r'\s+', ' ', regex=True)

#Remove prefixed 'b'
X_train = X_train.str.replace(r'^b\s+', '', regex=True)
X_test= X_test.str.replace(r'^b\s+', '', regex=True)

#Convert to Lowercase
X_train = X_train.str.lower()
X_test= X_test.str.lower()

## Now let's work on removing stopwords
Remove the stopwords.

In [8]:
from nltk.corpus import stopwords

stop_words_en = set(stopwords.words('english'))

In [9]:
def del_stopwords(text, stopwords):
    words = text.lower().split()
    result = [p for p in words if p not in stopwords]
    return result


X_train_clean = X_train.apply(lambda t: del_stopwords(t, stop_words_en))
X_test_clean = X_test.apply(lambda t: del_stopwords(t, stop_words_en))

print(X_train_clean.head())

442    [dear, good, day, hope, fine, cdear, writting,...
962    [mr, henry, kaborethe, chief, auditor, incharg...
971                                                   []
190    [desk, dr, adamu, ismalerauditing, accounting,...
551    [dear, friend, name, loi, estrada, wife, mr, j...
Name: text, dtype: object

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [12]:
from nltk.stem.wordnet import WordNetLemmatizer
import nltk

nltk.download('wordnet') 


lemmatizer = WordNetLemmatizer()

def lemmatize_words(words):
    return [lemmatizer.lemmatize(w) for w in words]

X_train_lemma = X_train_clean.apply(lemmatize_words)
X_test_lemma = X_test_clean.apply(lemmatize_words)

print(X_train_lemma.head())

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\alber\AppData\Roaming\nltk_data...

442    [dear, good, day, hope, fine, cdear, writting,...
962    [mr, henry, kaborethe, chief, auditor, incharg...
971                                                   []
190    [desk, dr, adamu, ismalerauditing, accounting,...
551    [dear, friend, name, loi, estrada, wife, mr, j...
Name: text, dtype: object

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [13]:
from collections import Counter

df_train = pd.DataFrame({
    'words': X_train_lemma,
    'label': y_train
})

ham_words = df_train[df_train['label'] == 0]['words'].sum()   
spam_words = df_train[df_train['label'] == 1]['words'].sum()

print("Top 10 HAM:", Counter(ham_words).most_common(10))
print("Top 10 SPAM:", Counter(spam_words).most_common(10))

Top 10 HAM: [('â', 205), ('state', 97), ('president', 95), ('would', 92), ('mr', 90), ('ã', 87), ('obama', 80), ('percent', 80), ('call', 77), ('work', 72)]
Top 10 SPAM: [('money', 761), ('account', 674), ('u', 631), ('bank', 615), ('fund', 600), ('e', 523), ('transaction', 435), ('business', 412), ('country', 401), ('nbsp', 387)]

## Extra features

In [ ]:
data_train = pd.DataFrame({
    'preprocessed_text': X_train_lemma.apply(lambda words: " ".join(words)),
    'label': y_train
})

data_val = pd.DataFrame({
    'preprocessed_text': X_test_lemma.apply(lambda words: " ".join(words)),
    'label': y_test
})

In [20]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,preprocessed_text,label,money_mark,suspicious_words,text_len
442,dear good day hope fine cdear writting mail du...,1,1,1,1002
962,mr henry kaborethe chief auditor inchargeforei...,1,0,1,2015
971,,0,0,0,0
190,desk dr adamu ismalerauditing accounting manag...,1,1,1,383
551,dear friend name loi estrada wife mr josephest...,1,1,1,1475

## How would work the Bag of Words with Count Vectorizer concept?

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()

X_train_bow = count_vectorizer.fit_transform(data_train['preprocessed_text'])
X_test_bow = count_vectorizer.transform(data_val['preprocessed_text'])

print(X_train_bow.shape)
print(X_test_bow.shape)

(800, 28340)
(200, 28340)

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [22]:
tfidf_vectorizer = TfidfVectorizer()  # ya está importado en la celda 3

X_train_tfidf = tfidf_vectorizer.fit_transform(data_train['preprocessed_text'])
X_test_tfidf = tfidf_vectorizer.transform(data_val['preprocessed_text'])

print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(800, 28340)
(200, 28340)

## And the Train a Classifier?

In [23]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

clf = MultinomialNB()
clf.fit(X_train_tfidf, y_train)

y_pred = clf.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.945
              precision    recall  f1-score   support

           0       1.00      0.90      0.95       112
           1       0.89      1.00      0.94        88

    accuracy                           0.94       200
   macro avg       0.94      0.95      0.94       200
weighted avg       0.95      0.94      0.95       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code