from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [58]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [59]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [63]:
from sklearn.model_selection import train_test_split

possible_text_cols = ["text", "message", "sms", "email", "content", "body"]
possible_label_cols = ["label", "spam", "target", "class", "category", "v1"]

text_col = next((c for c in possible_text_cols if c in data.columns), None)
label_col = next((c for c in possible_label_cols if c in data.columns), None)

# print("Detected text_col:", text_col)   # check the text column
# print("Detected label_col:", label_col)  # check label column

data_train, data_val = train_test_split(
    data,
    test_size=0.2,
    random_state=42,
    stratify=data[label_col] if label_col is not None else None
)

print("Train:", data_train.shape)
print("Val:", data_val.shape)

Train: (800, 2)
Val: (200, 2)

## Data Preprocessing

In [64]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [66]:
import re

def strip_html(raw_text: str) -> str:

    #1 remove inline JS/CSS
    text = re.sub(r"(<script.*?>.*?<\/script>)", " ", raw_text, flags=re.DOTALL|re.IGNORECASE)
    text = re.sub(r"(<style.*?>.*?<\/style>)", " ", text, flags=re.DOTALL|re.IGNORECASE)

    #2 remove HTML comments
    text = re.sub(r"(<!--,*?-->)", " ", text, flags=re.DOTALL)

    #3 remove remaining tags
    text = re.sub(r"<.*?>+", " ", text)

    return text

data_train["preprocessing_text"] = data_train[text_col].apply(strip_html)
data_val["preprocessing_text"] = data_val[text_col].apply(strip_html)

data_train[["preprocessing_text"]].head()

                                    preprocessing_text
442  Dear=2C Good day hope fine=2Cdear am writting ...
962  FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...
971                                           Will do.
190  FROM THE DESK OF DR.ADAMU  ISMALERAUDITING AND...
551  Dear Friend, My name is LOI C.ESTRADA,The wife...

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [74]:
import re


# data_train[["preprocessing_text"]].head() # check html removal

def clean_text(text: str) -> str:
    # Remove all the special characters
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # remove numbers
    text = re.sub(r"\d+", " ", text)

    # remove all single characters
    text = re.sub(r"\s+[a-zA-Z]\s+", " ", text)

    # remove single characters from the start
    text = re.sub(r"^[a-zA-Z]\s+", " ", text)

    # Substitute multiple spaces with single space
    text = re.sub(r"\s+", " ", text).strip()

    # Remove prefix "b"
    text = re.sub(r"^b\s+", "", text)



    # Convert to Lowercase
    text = text.lower()

    # Remove short tokens (1-2 letters) # extra clean
    text = " ".join([w for w in text.split() if len(w) > 2])


    return text


example = data_train[text_col].iloc[0]
print("RAW:", example)
print("//////////////////////////")
print("CLEAN:", clean_text(strip_html(str(example)))) # check data after changes

RAW: Dear=2C Good day hope fine=2Cdear am writting this mail with due respect and heartful of tears since we have not known or met ourselves previously I am asking for your assistance=2Ci have will be very glad if you can render me assistance to my situation now=2E I will make my proposal well known if I am given the opportunity=2E I would like to use this opportunity to introduce myself to you=2E Am Miss Johana Johnpaul 24 years old girl from Liberia =2Cthe only daughter of Late Godwin Johnpaul the deputy minister of national security under the leadership of president Charles Taylor of liberia who is now in exile after many innocent soul were killed=2E My father was killed by the government of CharlesTaylor=2Cheaccuse my father of coup attempt and after a month my mother Cynthia was also killed=2E The main reason why I am contacting you now is to seek for your assistance in the area of my future investment and also i want to hand over some huge amount of money to you=2E This money is Ten Millon Five Hundred Thousand US Dollars which was deposited some years ago by my father he made me the sole beneficiary=2Fnext of kin to the money=2E I am now asking you to stand on my behalf to make this claim for the bank=2Cam a girl and too young in age cann't handle this can of transaction=2Ci want you to stand as my foregin partner oversea and also to help me investment the money as well send me your telephone number and pictures ok=2E=2E=2E=2E I have all original copies of the documents concering this money with me here=2CSo please am expecting to hear from you soon=2E My Regards=2C Miss Johana
//////////////////////////
CLEAN: dear good day hope fine cdear writting this mail with due respect and heartful tears since have not known met ourselves previously asking for your assistance have will very glad you can render assistance situation now will make proposal well known given the opportunity would like use this opportunity introduce myself you miss johana johnpaul years old girl from liberia cthe only daughter late godwin johnpaul the deputy minister national security under the leadership president charles taylor liberia who now exile after many innocent soul were killed father was killed the government charlestaylor cheaccuse father coup attempt and after month mother cynthia was also killed the main reason why contacting you now seek for your assistance the area future investment and also want hand over some huge amount money you this money ten millon five hundred thousand dollars which was deposited some years ago father made the sole beneficiary fnext kin the money now asking you stand behalf make this claim for the bank cam girl and too young age cann handle this can transaction want you stand foregin partner oversea and also help investment the money well send your telephone number and pictures have all original copies the documents concering this money with here cso please expecting hear from you soon regards miss johana

## Now let's work on removing stopwords
Remove the stopwords.

In [81]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords') #download stopwords so they can be removed from the set

stop_words = set(stopwords.words("english")) # create a stop words set

list(sorted(list(stop_words)))[:20]

def remove_stopwords(text: str) -> str: # function for removing the stop words
    tokens = text.split()
    tokens = [text for text in tokens if text not in stop_words]
    return " ".join(tokens)

data_train["preprocessing_text"] = data_train["preprocessing_text"].apply(remove_stopwords)
data_val["preprocessing_text"] = data_val["preprocessing_text"].apply(remove_stopwords)

data_train[["preprocessing_text"]].head() # check stopwords removal

print(f"CLEAN: {clean_text(data_train["preprocessing_text"].iloc[0])}")
print("//////////////////////////")
print(f"Preprocessed: {data_train["preprocessing_text"].iloc[0]}")

CLEAN: dear good day hope fine cdear writting mail due respect heartful tears since known met previously asking assistance glad render assistance situation now make proposal well known given opportunity would like use opportunity introduce you miss johana johnpaul years old girl liberia cthe daughter late godwin johnpaul deputy minister national security leadership president charles taylor liberia exile many innocent soul killed father killed government charlestaylor cheaccuse father coup attempt month mother cynthia also killed the main reason contacting seek assistance area future investment also want hand huge amount money you this money ten millon five hundred thousand dollars deposited years ago father made sole beneficiary fnext kin money asking stand behalf make claim bank cam girl young age cann handle transaction want stand foregin partner oversea also help investment money well send telephone number pictures original copies documents concering money here cso please expecting hear soon regards miss johana
//////////////////////////
Preprocessed: Dear=2C Good day hope fine=2Cdear writting mail due respect heartful tears since known met previously I asking assistance=2Ci glad render assistance situation now=2E I make proposal well known I given opportunity=2E I would like use opportunity introduce you=2E Am Miss Johana Johnpaul 24 years old girl Liberia =2Cthe daughter Late Godwin Johnpaul deputy minister national security leadership president Charles Taylor liberia exile many innocent soul killed=2E My father killed government CharlesTaylor=2Cheaccuse father coup attempt month mother Cynthia also killed=2E The main reason I contacting seek assistance area future investment also want hand huge amount money you=2E This money Ten Millon Five Hundred Thousand US Dollars deposited years ago father made sole beneficiary=2Fnext kin money=2E I asking stand behalf make claim bank=2Cam girl young age cann't handle transaction=2Ci want stand foregin partner oversea also help investment money well send telephone number pictures ok=2E=2E=2E=2E I original copies documents concering money here=2CSo please expecting hear soon=2E My Regards=2C Miss Johana

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ben_h\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [83]:

from nltk.stem import WordNetLemmatizer


# create the lemmatizer
lemmatizer = WordNetLemmatizer()

# define the lemmatizer function
def lemmatizer_text (text: str) -> str:
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(text) for text in tokens]
    return " ".join(tokens)

# apply train and validation lemmatizer
data_train["preprocessed_text"] = data_train["preprocessing_text"].apply(lemmatizer_text)
data_val["preprocessed_text"] = data_val["preprocessing_text"].apply(lemmatizer_text)

data_train[["preprocessed_text"]].head() # check lemmatization

CLEAN: dear good day hope fine cdear writting mail due respect heartful tears since known met previously asking assistance glad render assistance situation now make proposal well known given opportunity would like use opportunity introduce you miss johana johnpaul years old girl liberia cthe daughter late godwin johnpaul deputy minister national security leadership president charles taylor liberia exile many innocent soul killed father killed government charlestaylor cheaccuse father coup attempt month mother cynthia also killed the main reason contacting seek assistance area future investment also want hand huge amount money you this money ten millon five hundred thousand dollars deposited years ago father made sole beneficiary fnext kin money asking stand behalf make claim bank cam girl young age cann handle transaction want stand foregin partner oversea also help investment money well send telephone number pictures original copies documents concering money here cso please expecting hear soon regards miss johana

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [70]:
from collections import Counter

data_train.columns

# data_train[label_col].value_counts()  # Label: 0     446
                                        # Label: 1     356

ham_df = data_train[data_train[label_col].astype(str) == "0"]
spam_df = data_train[data_train[label_col].astype(str) == "1"]

def top_words(df, n=10):
    words = " ".join(df["preprocessed_text"]).split()
    return Counter(words).most_common(n)

print("Top 10 HAM words:", top_words(ham_df, 10))
print("Top 10 SPAM words:", top_words(spam_df, 10))

Top 10 HAM words: [('I', 173), ('2', 160), ('1', 129), ('The', 103), ('3', 103), ('would', 89), ('-', 72), ('percent', 68), ('call', 62), ('4', 61)]
Top 10 SPAM words: [('I', 2025), ('THE', 590), ('money', 558), ('TO', 495), ('OF', 474), ('account', 410), ('fund', 408), ('AND', 392), ('business', 286), ('bank', 284)]

## Extra features

In [71]:
import html

# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 


# additional cleaning of this data.
def normalize_html_entities(text: str) -> str:
    text = html.unescape(text)      # converts &nbsp; to \xa0, etc.
    text = text.replace("\xa0", " ")  # convert NBSP to normal space
    return text

data_train["preprocessing_text"] = data_train["preprocessing_text"].apply(normalize_html_entities)
data_val["preprocessing_text"] = data_val["preprocessing_text"].apply(normalize_html_entities)

data_train.head()

,text,label,preprocessing_text,preprocessed_text,money_mark,suspicious_words,text_len
442,Dear=2C Good day hope fine=2Cdear am writting ...,1,Dear=2C Good day hope fine=2Cdear writting mai...,Dear=2C Good day hope fine=2Cdear writting mai...,0,1,1106
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,1,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,1,1,2153
971,Will do.,0,Will do.,Will do.,0,0,8
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,1,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND ...,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND ...,1,1,448
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",1,"Dear Friend, My name LOI C.ESTRADA,The wife Mr...","Dear Friend, My name LOI C.ESTRADA,The wife Mr...",1,1,1627

## How would work the Bag of Words with Count Vectorizer concept?

In [85]:
from sklearn.feature_extraction.text import CountVectorizer

bow_vectorizer = CountVectorizer(max_features=5000)

X_train_bow = bow_vectorizer.fit_transform(data_train["preprocessing_text"])

X_val_bow = bow_vectorizer.transform(data_val["preprocessing_text"])

print("X_train_bow shape:", X_train_bow.shape)
print("X_val_bow shape:", X_val_bow.shape)

list(bow_vectorizer.vocabulary_.keys())[:20]

X_train_bow shape: (800, 5000)
X_val_bow shape: (200, 5000)

['dear',
 '2c',
 'good',
 'day',
 'hope',
 'fine',
 'writting',
 'mail',
 'due',
 'respect',
 'heartful',
 'tears',
 'since',
 'known',
 'met',
 'previously',
 'asking',
 'assistance',
 '2ci',
 'glad']

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [86]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf_vectorizer.fit_transform(data_train["preprocessing_text"])

X_val_tfidf = tfidf_vectorizer.transform(data_val["preprocessing_text"])

print("X_train_tfidf shape:", X_train_tfidf.shape)
print("X_val_tfidf shape:", X_val_tfidf.shape)

X_train_tfidf shape: (800, 5000)
X_val_tfidf shape: (200, 5000)

## And the Train a Classifier?

In [87]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_train = data_train["label"]
y_val = data_val["label"]

clf = MultinomialNB()

clf.fit(X_train_tfidf, y_train)

y_pred = clf.predict(X_val_tfidf)

print("Accuracy:", accuracy_score(y_val, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))

Accuracy: 0.985
Confusion matrix:
 [[109   3]
 [  0  88]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       112
           1       0.97      1.00      0.98        88

    accuracy                           0.98       200
   macro avg       0.98      0.99      0.98       200
weighted avg       0.99      0.98      0.99       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [88]:
from scipy.sparse import hstack, csr_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

y_train = data_train["label"]
y_val = data_val["label"]

def eval_nb(Xtr, Xva, name):
    clf = MultinomialNB()  # default params (required)
    clf.fit(Xtr, y_train)
    pred = clf.predict(Xva)
    acc = accuracy_score(y_val, pred)
    print(f"{name} accuracy: {acc:.4f}")
    return acc

acc_bow = eval_nb(X_train_bow, X_val_bow, "BoW only")

acc_tfidf = eval_nb(X_train_tfidf, X_val_tfidf, "TF-IDF only")

extra_cols = ["money_mark", "suspicious_words", "text_len"]

X_train_extra = csr_matrix(data_train[extra_cols].values)
X_val_extra = csr_matrix(data_val[extra_cols].values)

X_train_bow_plus = hstack([X_train_bow, X_train_extra])
X_val_bow_plus = hstack([X_val_bow, X_val_extra])

acc_bow_plus = eval_nb(X_train_bow_plus, X_val_bow_plus, "BoW + flags")

X_train_tfidf_plus = hstack([X_train_tfidf, X_train_extra])
X_val_tfidf_plus = hstack([X_val_tfidf, X_val_extra])

acc_tfidf_plus = eval_nb(X_train_tfidf_plus, X_val_tfidf_plus, "TF-IDF + flags")

BoW only accuracy: 0.9700
TF-IDF only accuracy: 0.9850
BoW + flags accuracy: 0.9650
TF-IDF + flags accuracy: 0.9250

So it appears that the most relevant feature are : TF-IDF for getting 0.985 validation accuracy in the test.

These: = ["money_mark", "suspicious_words", "text_len"] did not help, they actually show they did worse in the test here as both IDF and Bow show worse performance.