In [1]:
#from IPython.core.display import display, HTML
#display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM
## THIS HAS A DATA LEEK BECAUSE OF THE FEATURE ENGINEERING AN SPLITTING PROCESS

### Let's prepare the environment

In [2]:
import pandas as pd
import re
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [3]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

In [4]:
data

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [5]:
# Let's divide the training and test set into two partitions
data_all_train = pd.read_csv("../data/kg_train.csv",encoding='latin-1')
data_all_train.fillna("",inplace=True)
data_all_test = pd.read_csv("../data/kg_test.csv",encoding='latin-1')
data_all_test.fillna("",inplace=True)

## Data Preprocessing

In [6]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
from nltk.stem import WordNetLemmatizer       
snowball = SnowballStemmer('english')
lemmatizer = WordNetLemmatizer()

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [7]:
## Now, we have to clean the html code removing words
## First we remove inline JavaScript/CSS
def remove_inline_css_js(text):
    # Remove inline CSS styles
    text = re.sub(r'style="[^"]*"', '', text)
    # Remove inline JavaScript (e.g., event handlers like onclick)
    text = re.sub(r'\s*on\w+="[^"]*"', '', text)
    # Remove entire <script> tags and their content
    text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.DOTALL)
    ## Your code here
    return text
## Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters

def remove_html_comments(text):
    # Remove HTML comments
    text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)
    return text

## Next we can remove the remaining tags
def remove_html_tags(text):
    # Remove HTML tags
    text = re.sub(r'<[^>]+>', '', text)
    return text

def remove_multiline_comments(text):
    # Remove multi-line comments (e.g., /* comment */)
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
    return text

# preprocess_text master func the text data
def preprocess_html_text(text):
    text = remove_inline_css_js(text)
    text = remove_html_comments(text)
    text = remove_html_tags(text)
    text = remove_multiline_comments(text)
    return text 


data_all_train['cleaned_text'] = data_all_train['text'].apply(lambda x: preprocess_html_text(x))
data_all_test['cleaned_text'] = data_all_test['text'].apply(lambda x: preprocess_html_text(x))

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [8]:
data_all_train['cleaned_text']

0       DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...
1                                                Will do.
2       Nora--Cheryl has emailed dozens of memos about...
3       Dear Sir=2FMadam=2C I know that this proposal ...
4                                                     fyi
                              ...
5959    I talked to CDM about doing some strategy sess...
5960    Dear Sir/CEO,=20I am Mr.D S Ammer, the purchas...
5961                                   Faxing to you now.
5962    Goodday,I am Joseph vaye,the son of late Issac...
5963    Hello my dearMy name is Prince George Sanoussi...
Name: cleaned_text, Length: 5964, dtype: object

In [9]:
# Remove all the special characters
# - Remove numbers
# - Remove all single characters
# - Remove single characters from the start
# - Substitute multiple spaces with single space
# - Remove prefixed 'b'
# - Convert to Lowercase
def preprocess_text_step_2(text):
    # Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    # Remove numbers
    text = re.sub(r'\d+', ' ', text)
    # Remove all single characters
    text = re.sub(r'\s+[a-zA-Z]\s+', ' ', text)
    # Remove single characters from the start
    text = re.sub(r'\^[a-zA-Z]\s+', ' ', text) 
    # Substitute multiple spaces with single space
    text = re.sub(r'\s+', ' ', text, flags=re.I)
    # Remove prefixed 'b'
    text = re.sub(r'^b\s+', '', text)
    # Convert to Lowercase
    text = text.lower()
    return text
    
data_all_train['cleaned_text'] = data_all_train['cleaned_text'].apply(lambda x: preprocess_text_step_2(x))
data_all_test['cleaned_text'] = data_all_test['cleaned_text'].apply(lambda x: preprocess_text_step_2(x))

## Now let's work on removing stopwords
# Remove the stopwords.
## Tame Your Text with Lemmatization
# Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run")

In [10]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

def remove_stopwords_stem_lemmatization(text):
    # take the punctuation list but drop the $ sign
    #punc_list = list(string.punctuation)
    #punc_list.remove('$')

    words = text.split()
    #flitered_punctuation = [word for word in words if word not in punc_list]
    filtered_words = [snowball.stem(word) for word in words if word not in stop_words]
    lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]
    
    return lemmatized_words

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/smithn5/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [11]:
data_all_train['cleaned_text']

0       dear sir strictly private business proposal am...
1                                                will do
2       nora cheryl has emailed dozens of memos about ...
3       dear sir fmadam i know that this proposal migh...
4                                                     fyi
                              ...
5959    i talked to cdm about doing some strategy sess...
5960    dear sir ceo am mr s ammer the purchasing dire...
5961                                   faxing to you now
5962    goodday am joseph vaye the son of late issac n...
5963    hello my dearmy name is prince george sanoussi...
Name: cleaned_text, Length: 5964, dtype: object

In [12]:
data_all_train['processed_text'] = data_all_train['cleaned_text'].apply(lambda x: remove_stopwords_stem_lemmatization(x))
data_all_test['processed_text'] = data_all_test['cleaned_text'].apply(lambda x: remove_stopwords_stem_lemmatization(x))

In [13]:
data_all_train[['processed_text', 'cleaned_text']]

,processed_text,cleaned_text
0,"[dear, sir, strict, privat, busi, propos, mike...",dear sir strictly private business proposal am...
1,[],will do
2,"[nora, cheryl, email, dozen, memo, haiti, week...",nora cheryl has emailed dozens of memos about ...
3,"[dear, sir, fmadam, know, propos, might, surpr...",dear sir fmadam i know that this proposal migh...
4,[fyi],fyi
...,...,...
5959,"[talk, cdm, strategi, session, week, discus, t...",i talked to cdm about doing some strategy sess...
5960,"[dear, sir, ceo, mr, ammer, purchas, director,...",dear sir ceo am mr s ammer the purchasing dire...
5961,[fax],faxing to you now
5962,"[goodday, joseph, vay, son, late, issac, nuhan...",goodday am joseph vaye the son of late issac n...
5963,"[hello, dearmi, name, princ, georg, sanoussi, ...",hello my dearmy name is prince george sanoussi...

In [14]:
# drop lines with empty processed_text
data_all_train = data_all_train[data_all_train['processed_text'].map(lambda x: len(x)) > 0]
data_all_test = data_all_test[data_all_test['processed_text'].map(lambda x: len(x)) > 0]

In [15]:
data_all_train[['processed_text', 'cleaned_text']]

,processed_text,cleaned_text
0,"[dear, sir, strict, privat, busi, propos, mike...",dear sir strictly private business proposal am...
2,"[nora, cheryl, email, dozen, memo, haiti, week...",nora cheryl has emailed dozens of memos about ...
3,"[dear, sir, fmadam, know, propos, might, surpr...",dear sir fmadam i know that this proposal migh...
4,[fyi],fyi
5,"[sure, bottom, line, need, special, secur, cod...",sure bottom line you need special security cod...
...,...,...
5959,"[talk, cdm, strategi, session, week, discus, t...",i talked to cdm about doing some strategy sess...
5960,"[dear, sir, ceo, mr, ammer, purchas, director,...",dear sir ceo am mr s ammer the purchasing dire...
5961,[fax],faxing to you now
5962,"[goodday, joseph, vay, son, late, issac, nuhan...",goodday am joseph vaye the son of late issac n...
5963,"[hello, dearmi, name, princ, georg, sanoussi, ...",hello my dearmy name is prince george sanoussi...

## Bag Of Words
Let's get the 10 top words

In [16]:
data_all_train

,text,label,cleaned_text,processed_text
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",1,dear sir strictly private business proposal am...,"[dear, sir, strict, privat, busi, propos, mike..."
2,Nora--Cheryl has emailed dozens of memos about...,0,nora cheryl has emailed dozens of memos about ...,"[nora, cheryl, email, dozen, memo, haiti, week..."
3,Dear Sir=2FMadam=2C I know that this proposal ...,1,dear sir fmadam i know that this proposal migh...,"[dear, sir, fmadam, know, propos, might, surpr..."
4,fyi,0,fyi,[fyi]
5,sure -- bottom line - you need a special secur...,0,sure bottom line you need special security cod...,"[sure, bottom, line, need, special, secur, cod..."
...,...,...,...,...
5959,I talked to CDM about doing some strategy sess...,0,i talked to cdm about doing some strategy sess...,"[talk, cdm, strategi, session, week, discus, t..."
5960,"Dear Sir/CEO,=20I am Mr.D S Ammer, the purchas...",1,dear sir ceo am mr s ammer the purchasing dire...,"[dear, sir, ceo, mr, ammer, purchas, director,..."
5961,Faxing to you now.,0,faxing to you now,[fax]
5962,"Goodday,I am Joseph vaye,the son of late Issac...",1,goodday am joseph vaye the son of late issac n...,"[goodday, joseph, vay, son, late, issac, nuhan..."
5963,Hello my dearMy name is Prince George Sanoussi...,1,hello my dearmy name is prince george sanoussi...,"[hello, dearmi, name, princ, georg, sanoussi, ..."

In [17]:
# Your code
# Let's get the 10 top words
from collections import Counter
def get_top_n_words(corpus, n=None):
    # Flatten the list of lists into a single list of words
    all_words = [word for tokens in corpus for word in tokens]
    # Use Counter to count the frequency of each word
    word_counts = Counter(all_words)
    # Get the n most common words
    top_n_words = word_counts.most_common(n)
    return top_n_words

In [18]:
get_top_n_words(data_all_train['processed_text'], n=10)

[('money', 5707),
 ('bank', 5375),
 ('account', 5145),
 ('u', 4528),
 ('fund', 4453),
 ('nbsp', 3707),
 ('e', 3481),
 ('mr', 3192),
 ('foreign', 3165),
 ('countri', 3038)]

## Extra features

In [ ]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])
# function that itrate over a list of strings and checks if any of the words in the list of string is a given text then returns True else False breack if found
def contains_any(list_texts, word_list):
    for text in list_texts:
        if text in word_list:
            return True
    return False



data_all_train['money_mark'] = data_all_train['processed_text'].apply(lambda x: contains_any(x, money_simbol_list))*1
data_all_train['suspicious_words'] = data_all_train['processed_text'].apply(lambda x: contains_any(x, suspicious_words))*1
data_all_train['text_len'] = data_all_train['processed_text'].apply(lambda x: len(x)) 

data_all_test['money_mark'] = data_all_test['processed_text'].apply(lambda x: contains_any(x, money_simbol_list))*1
data_all_test['suspicious_words'] = data_all_test['processed_text'].apply(lambda x: contains_any(x, suspicious_words))*1
data_all_test['text_len'] = data_all_test['processed_text'].apply(lambda x: len(x)) 

data_all_train.head()

,text,label,cleaned_text,processed_text,money_mark,suspicious_words,text_len
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",1,dear sir strictly private business proposal am...,"[dear, sir, strict, privat, busi, propos, mike...",1,1,202
2,Nora--Cheryl has emailed dozens of memos about...,0,nora cheryl has emailed dozens of memos about ...,"[nora, cheryl, email, dozen, memo, haiti, week...",0,0,17
3,Dear Sir=2FMadam=2C I know that this proposal ...,1,dear sir fmadam i know that this proposal migh...,"[dear, sir, fmadam, know, propos, might, surpr...",1,1,186
4,fyi,0,fyi,[fyi],0,0,1
5,sure -- bottom line - you need a special secur...,0,sure bottom line you need special security cod...,"[sure, bottom, line, need, special, secur, cod...",0,1,44

## How would work the Bag of Words with Count Vectorizer concept?

In [24]:
# back to one string from list of strings
data_all_train['preprocessed_text'] = data_all_train['processed_text'].apply(lambda x: ' '.join(x))
data_all_test['preprocessed_text'] = data_all_test['processed_text'].apply(lambda x: ' '.join(x))

## TF-IDF

- Load the vectorizer 
- Vectorize all dataset

- print the shape of the vetorized dataset

In [ ]:
# Load the TF-IDF vectorizer
tf_vectorizer = TfidfVectorizer()
# vevorize the data set
tfidf_train = tf_vectorizer.fit_transform(data_all_train['preprocessed_text'])
tfidf_test = tf_vectorizer.transform(data_all_test['preprocessed_text'])

In [27]:
y_train = data_all_train['label']

In [32]:
print("TF-IDF:\n", tfidf_train.toarray())
print("Vocabulary:", tf_vectorizer.get_feature_names_out())

TF-IDF:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Vocabulary: ['aa' 'aaa' 'aaaaagfxagbq' ... 'zzzahbxntx' 'zzzj' 'zzzs']

## And the Train a Classifier?

In [35]:
# Your Train a Classifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
X_train, X_test, y_train, y_test = train_test_split(tfidf_train, data_all_train['label'] , test_size=0.2, random_state=42)


classifier = make_pipeline(StandardScaler(with_mean=False), LogisticRegression())

In [36]:
# Train the classifier
classifier.fit(X_train, y_train)

# Make predictions
y_pred = classifier.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')
print(classification_report(y_test, y_pred))

Accuracy: 0.9889
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       680
           1       1.00      0.98      0.99       495

    accuracy                           0.99      1175
   macro avg       0.99      0.99      0.99      1175
weighted avg       0.99      0.99      0.99      1175

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code