In [11]:
#from IPython.core.display import display, HTML
#display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nicol\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [15]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

In [16]:
#data

### Let's divide the training and test set into two partitions

In [17]:
from sklearn.model_selection import train_test_split

data_train, data_val, label_train, label_val = train_test_split(data["text"],data["label"],test_size = 0.2, random_state=42)

## Data Preprocessing

In [18]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [19]:
# CSS is used for style ex: <h1 style="color:blue;">A Blue Heading</h1>
#Java is used to script inside the HTML: <script> document.getElementById("demo").innerHTML = "Hello javaScript!";</script>
from bs4 import BeautifulSoup

example_test = "I am trying to test the beautifulsoup <br><a href=3D'http://www.freeserve.com/anytime' style==3D'color:#0000FF; font-family:arial; font-size:10pt;' TARGET=3D'_blank'>ww=w.freeserve.com/anytime</a></span> library"

x = BeautifulSoup(example_test, "html.parser").get_text()
x

'I am trying to test the beautifulsoup ww=w.freeserve.com/anytime library'

In [20]:
#or this way also works
import re

reg_javacss = re.compile("(?i)<(\/?\w+)((\s+\w+(\s*=\s*(?:\".*?\"|'.*?'|[^'\">\s]+))?)+\s*|\s*)\/?>")

clean_example_test = reg_javacss.sub(u" ", x)
clean_example_test

'I am trying to test the beautifulsoup ww=w.freeserve.com/anytime library'

In [21]:
reg_htmlcomment = re.compile(r"https?://\S+|ww=w\.\S+|www\.\S+")

clean_comments_example_test = reg_htmlcomment.sub(u"", clean_example_test)
clean_comments_example_test

'I am trying to test the beautifulsoup  library'

In [22]:
type(data_train)

pandas.core.series.Series

In [23]:
#On kg train data removing html comments and javascripts with css: 

reg_htmlcomment = re.compile(r"https?://\S+|ww=w\.\S+|www\.\S+")

data_train_nojavahtml = [reg_htmlcomment.sub(" ", BeautifulSoup(item, "html.parser").get_text()) for item in data_train]

#data_train_nojavahtml

C:\Users\nicol\AppData\Local\Temp\ipykernel_39796\2908231161.py:5: MarkupResemblesLocatorWarning: The input passed in on this line looks more like a URL than HTML or XML.

If you meant to use Beautiful Soup to parse the web page found at a certain URL, then something has gone wrong. You should use an Python package like 'requests' to fetch the content behind the URL. Once you have the content as a string, you can feed that string into Beautiful Soup.

However, if you want to parse some data that happens to look like a URL, then nothing has gone wrong: you are using Beautiful Soup correctly, and this warning is spurious and can be filtered. To make this warning go away, run this code before calling the BeautifulSoup constructor:

    from bs4 import MarkupResemblesLocatorWarning
    import warnings

    warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)

  data_train_nojavahtml = [reg_htmlcomment.sub(" ", BeautifulSoup(item, "html.parser").get_text()) for item in data_train]

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [24]:
#Special characters
print(re.escape(string.punctuation))
#numbers 
print(r"\d+")
#single characters? tokenize?

!"\#\$%\&'\(\)\*\+,\-\./:;<=>\?@\[\\\]\^_`\{\|\}\~
\d+

In [25]:
#First, no characters or numbers 
char = re.compile(r'!"\#\&\(\)\*\+,\-\./:;<=>\?@\[\\\]\^_`\{\|\}\~') #no special characters but keeping the dollar to track later
no_num = re.compile(r"\d+") #no numbers
data_train_nonumchar =[no_num.sub(" ", char.sub(" ",(re.sub(r"\W", " ", item, flags=re.ASCII)))) for item in data_train_nojavahtml]
##yei, fixes accents
##data_train_nonumchar

In [53]:
#Second, single characters, for which I will split the sentences 
from nltk.tokenize import word_tokenize
train_tokens= [word_tokenize(item) for item in data_train_nonumchar]
train_tokens

[['REGARDS',
  'MR',
  'NELSON',
  'SMITH',
  'KINDLY',
  'REPLY',
  'ME',
  'ON',
  'MY',
  'PRIVATE',
  'EMAIL',
  'ADDRESS',
  'nelsonsmith',
  'yahoo',
  'com'],
 ['I',
  'have',
  'not',
  'been',
  'able',
  'to',
  'reach',
  'oscar',
  'this',
  'am',
  'We',
  'are',
  'supposed',
  'to',
  'send',
  'the',
  'pdb',
  'at',
  'Can',
  'u',
  'receive',
  'it'],
 ['Huma',
  'Abedin',
  'B',
  'I',
  'm',
  'checking',
  'with',
  'Pat',
  'on',
  'the',
  'k',
  'will',
  'work',
  'with',
  'Jack',
  'Jake',
  'on',
  'rest',
  'Also',
  'Huma',
  'has',
  'for',
  'you',
  'a',
  'follow',
  'up',
  'memo',
  'from',
  'the',
  'prep',
  'call'],
 ['I',
  'can',
  'have',
  'it',
  'announced',
  'here',
  'on',
  'Monday',
  'can',
  't',
  'today'],
 ['BANK',
  'OF',
  'AFRICAAGENCE',
  'SAN',
  'PEDRO',
  'BP',
  'San',
  'Pedro',
  'Cote',
  'D',
  'Ivoire',
  'West',
  'Africa',
  'Dear',
  'Sir',
  'I',
  'am',
  'Mrs',
  'Dorise',
  'Marie',
  'FRANCOISE',
  'an',
  'accountant',
  'of',
  'auditing',
  'and',
  'accounting',
  'section',
  'of',
  'Bank',
  'of',
  'Africa',
  'in',
  'Cote',
  'D',
  'Ivoire',
  'With',
  'due',
  'respect',
  'and',
  'regard',
  'I',
  'wish',
  'to',
  'seek',
  'your',
  'urgent',
  'assistance',
  'to',
  'tr',
  'ansfer',
  'the',
  'sum',
  'of',
  'U',
  'S',
  'MILLION',
  'DOLLARS',
  'SEVEN',
  'MILLION',
  'FIVE',
  'HUNDRED',
  'TH',
  'OUSAND',
  'DOLLARS',
  'from',
  'the',
  'above',
  'mentioned',
  'bank',
  'This',
  'money',
  'belongs',
  'to',
  'one',
  'o',
  'f',
  'our',
  'customers',
  'Robert',
  'Rice',
  'who',
  'died',
  'in',
  'a',
  'plane',
  'crash',
  'with',
  'his',
  'wife',
  'an',
  'd',
  'the',
  'fund',
  'has',
  'been',
  'lying',
  'dormant',
  'with',
  'the',
  'bank',
  'with',
  'out',
  'any',
  'claim',
  'eit',
  'her',
  'from',
  'his',
  'family',
  'or',
  'relation',
  'up',
  'to',
  'date',
  'I',
  'am',
  'contacting',
  'you',
  'to',
  'act',
  'as',
  'the',
  'bonafide',
  'next',
  'of',
  'kin',
  'to',
  'the',
  'deceased',
  'Th',
  'ere',
  'is',
  'no',
  'risk',
  'in',
  'this',
  'transaction',
  'as',
  'all',
  'loope',
  'holes',
  'has',
  'been',
  'taken',
  'care',
  'of',
  'and',
  'all',
  'necessary',
  'informations',
  'as',
  'regards',
  'to',
  'this',
  'fund',
  'have',
  'been',
  'secu',
  'red',
  'Be',
  'notified',
  'that',
  'I',
  'am',
  'still',
  'working',
  'with',
  'the',
  'bank',
  'and',
  'it',
  's',
  'only',
  'me',
  'and',
  'my',
  'colleagues',
  'that',
  'are',
  'aware',
  'of',
  'this',
  'development',
  'thus',
  'treat',
  'this',
  'proposal',
  'a',
  's',
  'confidential',
  'and',
  'secret',
  'for',
  'our',
  'security',
  'I',
  'have',
  'served',
  'the',
  'bank',
  'faithfully',
  'for',
  'good',
  'number',
  'of',
  'years',
  'and',
  'am',
  'presen',
  'tly',
  'preparing',
  'for',
  'my',
  'retirement',
  'therefore',
  'I',
  'see',
  'this',
  'as',
  'a',
  'golden',
  'opportun',
  'ity',
  'to',
  'be',
  'comfortable',
  'in',
  'life',
  'after',
  'retirement',
  'As',
  'soon',
  'as',
  'this',
  'fund',
  'is',
  'secured',
  'into',
  'your',
  'account',
  'I',
  'will',
  'come',
  'over',
  'for',
  'th',
  'e',
  'collection',
  'of',
  'our',
  'due',
  'share',
  'The',
  'sharing',
  'mod',
  'is',
  'as',
  'follows',
  'for',
  'you',
  'the',
  'account',
  'owner',
  'for',
  'me',
  'an',
  'd',
  'my',
  'colleagues',
  'while',
  'will',
  'be',
  'set',
  'aside',
  'for',
  'expensis',
  'made',
  'during',
  'the',
  'transaction',
  'Looking',
  'foward',
  'to',
  'hearing',
  'from',
  'you',
  'My',
  'regards',
  'Mrs',
  'Dorise',
  'Marie',
  'Fran',
  'E',
  'oise__________________________________________________Do',
  'You',
  'Yahoo',
  'Tired',
  'of',
  'spam',
  'Yahoo',
  'Mail',
  'has',
  'the',
  'best',
  'spam',
  'protection',
  'around'],
 ['Dear',
  'Friend',
  'My',
  'proposal',
  'to',
  'you',
  'will',
  'be',
  'very',
  'surprising',
  'as',
  'we',
  'have',
  'not',
  'had',
  'any',
  'Personal',
  'contact',
  'before',
  'However',
  'I',
  'sincerely',
  'seek',
  'your',
  'confidence',
  'in',
  'this',
  'transaction',
  'which',
  'I',
  'propose',
  'to',
  'you',
  'as',
  'a',
  'person',
  'of',
  'transparency',
  'honesty',
  'and',
  'high',
  'caliber',
  'Let',
  'me',
  'first',
  'start',
  'by',
  'introducing',
  'myself',
  'properly',
  'to',
  'you',
  'My',
  'name',
  'is',
  'Ron',
  'Sinclear',
  'i',
  'was',
  'the',
  'Personal',
  'Assistance',
  'to',
  'the',
  'Haitian',
  'President',
  'I',
  'apologize',
  'if',
  'I',
  'have',
  'infringed',
  'on',
  'your',
  'privacy',
  'It',
  'may',
  'interest',
  'you',
  'to',
  'know',
  'that',
  'the',
  'former',
  'president',
  'of',
  'Haiti',
  'has',
  'been',
  'fighting',
  'serious',
  'war',
  'for',
  'United',
  'Democracy',
  'for',
  'quite',
  'some',
  'years',
  'now',
  'which',
  'has',
  'been',
  'backed',
  'all',
  'along',
  'by',
  'some',
  'foreign',
  'powerful',
  'countries',
  'Not',
  'quite',
  'long',
  'ago',
  'the',
  'American',
  'government',
  'ordered',
  'President',
  'Jean',
  'Bertrand',
  'Aristed',
  'to',
  'leave',
  'Haiti',
  'or',
  'be',
  'forced',
  'out',
  'of',
  'power',
  'by',
  'a',
  'Rabel',
  'force',
  'Knowing',
  'fully',
  'well',
  'the',
  'capabilities',
  'of',
  'America',
  'and',
  'other',
  'powerful',
  'members',
  'of',
  'the',
  'United',
  'Nations',
  'President',
  'Aristed',
  'decided',
  'and',
  'left',
  'the',
  'seat',
  'of',
  'power',
  'into',
  'exile',
  'in',
  'South',
  'Africa',
  'country',
  'to',
  'seek',
  'asylum',
  'now',
  'a',
  'new',
  'government',
  'is',
  'in',
  'place',
  'In',
  'the',
  'light',
  'of',
  'all',
  'these',
  'sad',
  'happenings',
  'there',
  'was',
  'this',
  'deposit',
  'he',
  'made',
  'with',
  'a',
  'Security',
  'Company',
  'in',
  'Europe',
  'in',
  'year',
  'May',
  'this',
  'took',
  'place',
  'while',
  'he',
  'was',
  'still',
  'in',
  'power',
  'as',
  'the',
  'president',
  'of',
  'Haiti',
  'through',
  'my',
  'aid',
  'his',
  'Personal',
  'Assistant',
  'Ron',
  'Sinclear',
  'and',
  'some',
  'loyalist',
  'he',
  'suceeded',
  'to',
  'secretely',
  'move',
  'the',
  'sum',
  'of',
  'M',
  'USD',
  'NINE',
  'MILLION',
  'FIVE',
  'HUNDERED',
  'THOUSAND',
  'UNITED',
  'STATES',
  'DOLLARS',
  'to',
  'a',
  'private',
  'security',
  'company',
  'vault',
  'in',
  'Europe',
  'Now',
  'we',
  'need',
  'your',
  'services',
  'as',
  'a',
  'highly',
  'reliable',
  'foreigner',
  'to',
  'receive',
  'the',
  'funds',
  'into',
  'your',
  'bank',
  'account',
  'for',
  'the',
  'future',
  'survival',
  'of',
  'my',
  'family',
  'because',
  'he',
  'Aristed',
  'can',
  'not',
  'presently',
  'operate',
  'any',
  'foreign',
  'bank',
  'account',
  'in',
  'his',
  'name',
  'These',
  'funds',
  'US',
  'm',
  'USD',
  'arose',
  'from',
  'various',
  'money',
  'i',
  'received',
  'from',
  'the',
  'sales',
  'of',
  'diamonds',
  'deals',
  'i',
  'had',
  'with',
  'President',
  'Charles',
  'Taylor',
  'of',
  'Liberia',
  'which',
  'are',
  'abound',
  'in',
  'great',
  'quantity',
  'around',
  'the',
  'coastal',
  'areas',
  'of',
  'liberia',
  'I',
  'have',
  'decided',
  'that',
  'if',
  'you',
  'are',
  'able',
  'assist',
  'us',
  'you',
  'shall',
  'be',
  'compensated',
  'with',
  'commission',
  'of',
  'the',
  'funds',
  'of',
  'this',
  'money',
  'shall',
  'be',
  'set',
  'aside',
  'to',
  'take',
  'care',
  'of',
  'any',
  'local',
  'or',
  'foreign',
  'expenses',
  'that',
  'might',
  'be',
  'incurred',
  'along',
  'the',
  'line',
  'My',
  'family',
  'will',
  'have',
  'the',
  'remaining',
  'of',
  'the',
  'funds',
  'It',
  'might',
  'also',
  'interest',
  'you',
  'to',
  'note',
  'that',
  'all',
  'security',
  'arrangements',
  'regarding',
  'this',
  'transaction',
  'has',
  'been',
  'put',
  'in',
  'place',
  'therefore',
  'you',
  'have',
  'nothing',
  'whatsoever',
  'to',
  'fear',
  'or',
  'worry',
  'about',
  'as',
  'every',
  'arrangement',
  'will',
  'be',
  'co',
  'handled',
  'by',
  'you',
  'and',
  'my',
  'former',
  'Personal',
  'Assistant',
  'Ron',
  'Sinclear',
  'who',
  'is',
  'now',
  'presentely',
  'in',
  'Europe',
  'The',
  'Netherlands',
  'for',
  'possible',
  'conclusion',
  'of',
  'this',
  'arrangement',
  'Most',
  'part',
  'of',
  'this',
  'share',
  'for',
  'my',
  'family',
  'will',
  'also',
  'be',
  'invested',
  'in',
  'a',
  'lucrative',
  'business',
  'courtesy',
  'of',
  'your',
  'full',
  'advice',
  'assistance',
  'and',
  'connections',
  'because',
  'that',
  'is',
  'the',
  'most',
  'importat',
  'part',
  'of',
  'this',
  'transaction',
  'As',
  'you',
  'indicate',
  'interest',
  'to',
  'assist',
  'my',
  'family',
  'please',
  'kindly',
  'send',
  'to',
  'us',
  'your',
  'telephone',
  'fax',
  'numbers',
  'for',
  'further',
  'discussion',
  'and',
  'clarification',
  'I',
  'will',
  'be',
  'expecting',
  'to',
  'receive',
  'your',
  'urgent',
  'response',
  'for',
  'us',
  'to',
  'proceed',
  'to',
  'more',
  'details',
  'on',
  'this',
  'pending',
  'transaction'],
 ['Soneri',
  'Bank',
  'LimitedSilver',
  'Jubilee',
  'Center',
  'CBritto',
  'Road',
  'C',
  'Garden',
  'East',
  'C',
  'Karachi',
  'CpakistanDear',
  'Sir',
  'FMadam',
  'CI',
  'am',
  'Mr',
  'Mr',
  'Zakir',
  'Mahmood',
  'official',
  'of',
  'Soneri',
  'Bank',
  'Limited',
  'EThis',
  'is',
  'an',
  'urgent',
  'and',
  'very',
  'confidential',
  'business',
  'proposition',
  'EOn',
  'June',
  'C',
  'Ca',
  'Foreign',
  'Oil',
  'consultant',
  'Fcontractor',
  'with',
  'the',
  'pakistan',
  'Asian',
  'Institute',
  'of',
  'Mining',
  'and',
  'Metallurgy',
  'C',
  'Mr',
  'Ekassim',
  'Hassan',
  'made',
  'a',
  'numbered',
  'time',
  'Fixed',
  'Deposit',
  'for',
  'twelve',
  'calendar',
  'months',
  'C',
  'valued',
  'at',
  'US',
  'C',
  'C',
  'E',
  'C',
  'Twenty',
  'six',
  'Million',
  'C',
  'five',
  'hundred',
  'thousand',
  'Dollars',
  'in',
  'my',
  'branch',
  'EUpon',
  'maturity',
  'CI',
  'sent',
  'a',
  'routine',
  'notification',
  'to',
  'his',
  'forwarding',
  'address',
  'Cbut',
  'got',
  'no',
  'reply',
  'E',
  'After',
  'a',
  'month',
  'Cwe',
  'sent',
  'a',
  'reminder',
  'and',
  'finally',
  'we',
  'discovered',
  'from',
  'his',
  'contract',
  'employers',
  'C',
  'the',
  'National',
  'Petroleum',
  'Corporation',
  'that',
  'Mr',
  'Ekassim',
  'Hassan',
  'died',
  'from',
  'an',
  'automobile',
  'accident',
  'EOn',
  'further',
  'investigation',
  'CI',
  'found',
  'out',
  'that',
  'he',
  'died',
  'without',
  'making',
  'a',
  'WILL',
  'Cand',
  'all',
  'attempts',
  'to',
  'trace',
  'his',
  'next',
  'of',
  'kin',
  'was',
  'fruitless',
  'EI',
  'therefore',
  'made',
  'further',
  'investigation',
  'and',
  'discovered',
  'that',
  'Mr',
  'Ekassim',
  'Hassandid',
  'not',
  'declare',
  'any',
  'kin',
  'or',
  'relations',
  'in',
  'all',
  'his',
  'official',
  'documents',
  'Cincluding',
  'his',
  'Bank',
  'Deposit',
  'paperwork',
  'in',
  'my',
  'Bank',
  'E',
  'This',
  'sum',
  'of',
  'US',
  'C',
  'C',
  'E',
  'has',
  'carefully',
  'been',
  'fixed',
  'in',
  'my',
  'bank',
  'for',
  'safe',
  'keeping',
  'ENo',
  'one',
  'will',
  'ever',
  'come',
  'forward',
  'to',
  'claim',
  'it',
  'EAccording',
  'to',
  'Asian',
  'Law',
  'C',
  'at',
  'the',
  'expiration',
  'of',
  'five',
  'years',
  'C',
  'the',
  'money',
  'will',
  'revert',
  'to',
  'the',
  'ownership',
  'of',
  'the',
  'Government',
  'if',
  'nobody',
  'applies',
  'to',
  'claim',
  'the',
  'fund',
  'EConsequently',
  'C',
  'my',
  'proposal',
  'is',
  'that',
  'I',
  'will',
  'like',
  'you',
  'as',
  'a',
  'Foreigner',
  'to',
  'stand',
  'in',
  'as',
  'the',
  'owner',
  'of',
  'the',
  'money',
  'which',
  'was',
  'fixed',
  'deposited',
  'in',
  'my',
  'bank',
  'E',
  'I',
  'am',
  'writing',
  'you',
  'because',
  'I',
  'as',
  'a',
  'public',
  'servant',
  'Ci',
  'can',
  'not',
  'operate',
  'a',
  'foreign',
  'account',
  'EI',
  'want',
  'to',
  'present',
  'you',
  'as',
  'the',
  'owner',
  'of',
  'the',
  'funds',
  'so',
  'you',
  'can',
  'be',
  'able',
  'to',
  'claim',
  'them',
  'with',
  'the',
  'help',
  'of',
  'my',
  'attorney',
  'EThis',
  'is',
  'simple',
  'EI',
  'will',
  'like',
  'you',
  'to',
  'provide',
  'immediately',
  'your',
  'full',
  'names',
  'and',
  'address',
  'so',
  'that',
  'the',
  'Attorney',
  'will',
  'prepare',
  'the',
  'necessary',
  'documents',
  'which',
  'will',
  'put',
  'you',
  'in',
  'place',
  'as',
  'the',
  'beneficiary',
  'of',
  'the',
  'funds',
  'EThe',
  'money',
  'will',
  'be',
  'moved',
  'out',
  'for',
  'us',
  'to',
  'share',
  'in',
  'the',
  'ratio',
  'of',
  'forme',
  'and',
  'for',
  'you',
  'E',
  'The',
  'paperwork',
  'for',
  'this',
  'transaction',
  'will',
  'be',
  'done',
  'by',
  'the',
  'Attorney',
  'and',
  'this',
  'will',
  'guarantees',
  'the',
  'successful',
  'execution',
  'of',
  'this',
  'transaction',
  'EIf',
  'you',
  'are',
  'interested',
  'C',
  'please',
  'reply',
  'immediately',
  'via',
  'my',
  'email',
  'and',
  'Upon',
  'your',
  'response',
  'CI',
  'shall',
  'then',
  'provide',
  'you',
  'with',
  'more',
  'details',
  'and',
  'relevant',
  'documents',
  'that',
  'will',
  'help',
  'you',
  'understand',
  'the',
  'transaction',
  'EPlease',
  'observe',
  'utmost',
  'confidentiality',
  'C',
  'and',
  'be',
  'rest',
  'assured',
  'that',
  'this',
  'transaction',
  'would',
  'be',
  'most',
  'profitable',
  'for',
  'both',
  'of',
  'us',
  'because',
  'I',
  'shall',
  'require',
  'your',
  'assistance',
  'to',
  'invest',
  'my',
  'share',
  'in',
  'real',
  'estate',
  'within',
  'your',
  'country',
  'EDue',
  'to',
  'the',
  'nature',
  'of',
  'confidentiality',
  'in',
  'this',
  'Transaction',
  'our',
  'communication',
  'can',
  'only',
  'be',
  'via',
  'email',
  'and',
  'fax',
  'mostly',
  'EThanks',
  'and',
  'my',
  'regards',
  'EZakir',
  'MahmoodSoneri',
  'Bank',
  'Limited'],
 ['Easy', 'Joy', 'Powerful', 'Yahoo', 'Bookmarks', 'x', 'Toolbar'],
 ['FROM',
  'AMR',
  'ECOLLINCE',
  'ADDOATTN',
  'AI',
  'NEED',
  'YOUR',
  'URGENT',
  'ASSISTANCESir',
  'C',
  'I',
  'want',
  'you',
  'to',
  'patiently',
  'read',
  'this',
  'offer',
  'E',
  'I',
  'am',
  'Mr',
  'ECollince',
  'Addo',
  'the',
  'Head',
  'of',
  'Delegation',
  'to',
  'the',
  'World',
  'Bank',
  'in',
  'West',
  'Africa',
  'EI',
  'am',
  'the',
  'linkman',
  'between',
  'the',
  'Organization',
  'For',
  'Petroleum',
  'Exporting',
  'Countries',
  'OPEC',
  'and',
  'the',
  'petroleum',
  'sector',
  'in',
  'the',
  'West',
  'African',
  'country',
  'EI',
  'also',
  'attend',
  'OPEC',
  'meetings',
  'constantly',
  'in',
  'Geneva',
  'E',
  'Through',
  'the',
  'sale',
  'of',
  'our',
  'allocated',
  'oil',
  'quota',
  'in',
  'OPEC',
  'CI',
  'was',
  'able',
  'to',
  'make',
  'US',
  'E',
  'million',
  'C',
  'Twenty',
  'seven',
  'millon',
  'Cfive',
  'hundred',
  'thousand',
  'us',
  'dollars',
  'which',
  'is',
  'currently',
  'deposited',
  'in',
  'a',
  'Security',
  'vault',
  'E',
  'I',
  'want',
  'you',
  'to',
  'assist',
  'me',
  'to',
  'claim',
  'this',
  'money',
  'as',
  'I',
  'can',
  'not',
  'claim',
  'it',
  'directly',
  'because',
  'I',
  'am',
  'still',
  'a',
  'Civil',
  'servant',
  'C',
  'and',
  'the',
  'code',
  'of',
  'conduct',
  'bureau',
  'forbid',
  'me',
  'to',
  'acquire',
  'such',
  'amount',
  'of',
  'money',
  'E',
  'It',
  'is',
  'on',
  'this',
  'basis',
  'that',
  'I',
  'am',
  'contacting',
  'you',
  'for',
  'assistance',
  'Cif',
  'you',
  'will',
  'be',
  'interested',
  'Bclaim',
  'documents',
  'will',
  'be',
  'process',
  'and',
  'send',
  'to',
  'you',
  'E',
  'The',
  'documents',
  'with',
  'which',
  'the',
  'fund',
  'are',
  'deposited',
  'will',
  'be',
  'changed',
  'Cto',
  'reflect',
  'you',
  'as',
  'the',
  'new',
  'beneficiary',
  'so',
  'that',
  'you',
  'will',
  'be',
  'Eligible',
  'to',
  'collect',
  'the',
  'fund',
  'on',
  'my',
  'behalf',
  'E',
  'I',
  'will',
  'give',
  'you',
  'of',
  'the',
  'fund',
  'for',
  'this',
  'assistance',
  'EI',
  'am',
  'aware',
  'of',
  'the',
  'international',
  'monitoring',
  'of',
  'all',
  'large',
  'scale',
  'financial',
  'movements',
  'after',
  'the',
  'September',
  'th',
  'terrorist',
  'attack',
  'on',
  'America',
  'and',
  'to',
  'avoid',
  'any',
  'state',
  'of',
  'financial',
  'investigation',
  'I',
  'will',
  'provide',
  'a',
  'classified',
  'clearance',
  'paper',
  'from',
  'the',
  'relevant',
  'bodies',
  'which',
  'will',
  'exonerate',
  'the',
  'money',
  'from',
  'either',
  'drug',
  'Cmoney',
  'laundered',
  'or',
  'terrorist',
  'related',
  'proceeds',
  'E',
  'Kindly',
  'respond',
  'to',
  'my',
  'proposal',
  'through',
  'this',
  'my',
  'private',
  'email',
  'Amrcollince',
  'Faddo',
  'hotmail',
  'Ecom',
  'indicating',
  'interest',
  'E',
  'I',
  'want',
  'to',
  'assure',
  'you',
  'that',
  'there',
  'is',
  'no',
  'risk',
  'attached',
  'in',
  'this',
  'transaction',
  'EYou',
  'should',
  'also',
  'provide',
  'me',
  'with',
  'your',
  'private',
  'telephone',
  'and',
  'fax',
  'numbers',
  'for',
  'easy',
  'communication',
  'E',
  'Expecting',
  'your',
  'response',
  'E',
  'Best',
  'regards',
  'C',
  'Mr',
  'ECollince',
  'Addo'],
 ['Dear',
  'Nancy',
  'I',
  'very',
  'much',
  'want',
  'to',
  'meet',
  'and',
  'we',
  've',
  'been',
  'trying',
  'to',
  'pin',
  'my',
  'schedule',
  'down',
  'enough',
  'to',
  'offer',
  'a',
  'date',
  'The',
  'only',
  'times',
  'I',
  'seefor',
  'me',
  'before',
  'December',
  'are',
  'Nov',
  'or',
  'sometime',
  'in',
  'the',
  'second',
  'or',
  'third',
  'weeks',
  'of',
  'December',
  'I',
  'm',
  'copying',
  'Cheryl',
  'soyou',
  'two',
  'can',
  'try',
  'to',
  'find',
  'a',
  'time',
  'that',
  'works',
  'As',
  'to',
  'the',
  'names',
  'I',
  'think',
  'they',
  're',
  'all',
  'worth',
  'inviting',
  'w',
  'the',
  'hope',
  'they',
  'can',
  'come',
  'Let',
  's',
  'do',
  'it',
  'Best',
  'H'],
 ['Just',
  'met',
  'with',
  'Fr',
  'Gudziak',
  'He',
  'will',
  'come',
  'back',
  'to',
  'Kyiv',
  'for',
  'your',
  'visit',
  'Also',
  'John',
  'Tefft',
  'saw',
  'him',
  'in',
  'Lviv',
  'He',
  'is',
  'so',
  'grateful',
  'for',
  'the',
  'strong',
  'support',
  'you',
  'have',
  'delivered',
  'Sent',
  'via',
  'BlackBerry',
  'from',
  'T',
  'Mobile'],
 ['No',
  'word',
  'back',
  'from',
  'chinese',
  'on',
  'his',
  'availability',
  'Blair',
  'will',
  'be',
  'fine',
  'with',
  'that'],
 ['When', 'is', 'Steinberg', 'call'],
 ['August', 'For', 'Hillary'],
 ['FROM',
  'MISS',
  'MARIA',
  'DENISEADDRESS',
  'AVE',
  'RUE',
  'ABIDJAN',
  'COTE',
  'D',
  'IVOIREDearest',
  'BelovedBase',
  'on',
  'your',
  'profile',
  'i',
  'am',
  'happy',
  'to',
  'request',
  'for',
  'your',
  'assistance',
  'and',
  'alsoto',
  'go',
  'into',
  'business',
  'partnership',
  'with',
  'you',
  'i',
  'believe',
  'that',
  'you',
  'will',
  'not',
  'betaryed',
  'my',
  'trust',
  'which',
  'i',
  'am',
  'going',
  'to',
  'lay',
  'on',
  'you',
  'I',
  'am',
  'MISS',
  'maria',
  'denise',
  'years',
  'old',
  'and',
  'the',

In [27]:
train_tokens[0]
#The tokens are individual items in each list, so we have to enter the sentence
nosingle_train_token= [[item for item in sentence if len(item)>1] for sentence in train_tokens]
#nosingle_train_token

In [28]:
#Empty spaces
reg_spaces = re.compile(r'/\s\s+/g')
nomultspaces_train_token = [[reg_spaces.sub(u" ", item) for item in sentence]for sentence in nosingle_train_token]
#nomultspaces_train_token

In [29]:
#prefixed b?
#should have been removed with the single characters previously

In [30]:
#Final change all to lowercase
data_train_clean= [[item.lower() for item in sentence] for sentence in nomultspaces_train_token]
#data_train_clean

## Now let's work on removing stopwords
Remove the stopwords.

In [31]:
#Importing the stopwords from english
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
type(stop_words)

set

In [32]:

data_train_clean_nostop = [[item for item in sentence if item not in stop_words]for sentence in data_train_clean]
#data_train_clean_nostop

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [33]:
import nltk
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
wordnet_lemma = WordNetLemmatizer()

In [34]:
def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    tag = nltk.pos_tag([word])[0][1][0]#  Get POS tag's first character (e.g., 'N' from 'NN')
    #Maps it to a WordNet-compatible tag
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    
    return tag_dict.get(tag, wordnet.NOUN) # returns the word type (Noun if we have not found)

In [35]:
#To lemmatize I first need to indicate the tag right?

data_train_nostop_lemm = [[wordnet_lemma.lemmatize(word,get_wordnet_pos(word)) for word in sentence] for sentence in data_train_clean_nostop]
#data_train_nostop_lemm

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [36]:
type(label_train)

pandas.core.series.Series

In [37]:
data_train_nostop_lemm[10]

['met',
 'fr',
 'gudziak',
 'come',
 'back',
 'kyiv',
 'visit',
 'also',
 'john',
 'tefft',
 'saw',
 'lviv',
 'grateful',
 'strong',
 'support',
 'deliver',
 'sent',
 'via',
 'blackberry',
 'mobile']

In [38]:
# ham = 0
# spam = 1
#redoing the dataframe for comparison
data_train_clean_dict = []

for i in range(len(data_train_nostop_lemm)): #that should be 800 
    entry = {"data_train":data_train_nostop_lemm[i], "label": label_train.iloc[i]}
    data_train_clean_dict.append(entry)
##data_train_clean_dict

In [39]:
data_train_clean_df = pd.DataFrame.from_dict(data_train_clean_dict)
data_train_clean_df.columns = ["preprocessed_text","class"]
#data_train_clean_df

In [40]:
data_train_ham= data_train_clean_df.loc[data_train_clean_df["class"]==0]
words_ham = []
for sentence in data_train_ham["preprocessed_text"]:
    for word in sentence:
        words_ham.append(word)
#call counter 
from collections import Counter
tf = Counter()
for word in words_ham:
    tf[word]+=1
print(tf.most_common(10))

[('state', 116), ('say', 104), ('pm', 97), ('call', 94), ('would', 93), ('work', 90), ('president', 89), ('mr', 89), ('time', 81), ('percent', 80)]

In [41]:
data_train_spam= data_train_clean_df.loc[data_train_clean_df["class"]==1]
words_spam = []
for sentence in data_train_spam["preprocessed_text"]:
    for word in sentence:
        words_spam.append(word)
#call counter 
from collections import Counter
tf = Counter()
for word in words_spam:
    tf[word]+=1
print(tf.most_common(10))

[('money', 842), ('account', 740), ('bank', 646), ('fund', 628), ('u', 593), ('transfer', 475), ('transaction', 468), ('business', 424), ('mr', 421), ('country', 419)]

## Extra features

In [42]:
data_val_dict= []

for i in range(len(data_val)): #that should be 800 
    entry = {"data_val":data_val.iloc[i], "label": label_val.iloc[i]}
    data_val_dict.append(entry)
data_val_df = pd.DataFrame.from_dict(data_val_dict)
data_val_df.columns=["preprocessed_text","class"]
data_val_df

                                     preprocessed_text  class
0    Dear Sir=2C I wish you go through this offer t...      1
1    To take your mind off the Balkans for a second...      0
2                         Pls keep the updates coming!      0
3    </STRONG><STRONG>CHRIST BETHEL HOSPITAL<BR>11 ...      1
4    sbwhoeopFriday February 5 2010 7:11 AMHRe: Bra...      0
..                                                 ...    ...
195  Sorry yes exactlyWe have shy tomorrow at 10am ...      0
196  DEAR=2CGOOD DAY=2EI KNOW THIS MESSAGE WILL COM...      1
197                                                FYI      0
198  Greetings Dear Friend Please Permit me to cont...      1
199  No in car on way to airport. Can you talk? Cal...      0

[200 rows x 2 columns]

In [43]:
data_train_clean_df["preprocessed_text"] =data_train_clean_df["preprocessed_text"].apply(" ".join)
data_train_clean_df

                                     preprocessed_text  class
0    regard mr nelson smith kindly reply private em...      1
1            able reach oscar suppose send pdb receive      0
2    huma abedin check pat work jack jake rest also...      0
3                                announce monday today      0
4    bank africaagence san pedro bp san pedro cote ...      1
..                                                 ...    ...
795  adama ibrahim_________________________________...      1
796                                      mean schedule      0
797  dear friend compliment guess letter may come s...      1
798  dear president fdirector name mr micheal ipenz...      1
799  let know today tomorrow work would rather find...      0

[800 rows x 2 columns]

In [44]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train_clean_df['money_mark'] = data_train_clean_df['preprocessed_text'].str.contains(money_simbol_list)*1
data_train_clean_df['suspicious_words'] = data_train_clean_df['preprocessed_text'].str.contains(suspicious_words)*1
data_train_clean_df['text_len'] = data_train_clean_df['preprocessed_text'].apply(lambda x: len(x)) 

data_val_df['money_mark'] = data_val_df['preprocessed_text'].str.contains(money_simbol_list)*1
data_val_df['suspicious_words'] = data_val_df['preprocessed_text'].str.contains(suspicious_words)*1
data_val_df['text_len'] = data_val_df['preprocessed_text'].apply(lambda x: len(x)) 

data_val_df.head()

,preprocessed_text,class,money_mark,suspicious_words,text_len
0,Dear Sir=2C I wish you go through this offer t...,1,0,1,2043
1,To take your mind off the Balkans for a second...,0,0,0,473
2,Pls keep the updates coming!,0,0,0,28
3,</STRONG><STRONG>CHRIST BETHEL HOSPITAL<BR>11 ...,1,1,1,2211
4,sbwhoeopFriday February 5 2010 7:11 AMHRe: Bra...,0,0,0,221

In [45]:
data_train_clean_df["preprocessed_text"][0]

'regard mr nelson smith kindly reply private email address nelsonsmith yahoo com'

## How would work the Bag of Words with Count Vectorizer concept?

In [46]:
#Considering that now all values in the column are now joined, with count vectorizer this should give a matrix for each value in the column

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [47]:
#Performing the fit only in the trained 
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

tdidf_train_matrix = vectorizer.fit_transform(data_train_clean_df['preprocessed_text'])
feature_names = vectorizer.get_feature_names_out() #this can help us build the lexicon
#all keys are the words for the lexicon. 
tdidf_train_array=tdidf_train_matrix.toarray()
#for i, doc_tfidf in enumerate(tdidf_train_array):
    #print(f"Document {i+1}:")
    #for j, score in enumerate(doc_tfidf):
        #if score > 0:
            #print(f"  {feature_names[j]}: {score:.4f}")
    #print()

In [48]:
tdidf_val_matrix = vectorizer.transform(data_val_df['preprocessed_text'])
feature_names = vectorizer.get_feature_names_out() #this can help us build the lexicon
#all keys are the words for the lexicon. 
tdidf_val_array=tdidf_val_matrix.toarray()
#for i, doc_tfidf in enumerate(tdidf_val_array):
    #print(f"Document {i+1}:")
    #for j, score in enumerate(doc_tfidf):
        #if score > 0:
            #print(f"  {feature_names[j]}: {score:.4f}")

## And the Train a Classifier?

In [49]:
# Your code

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [50]:
#using multinomial naives bayes with the TDIF only
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(tdidf_train_array, label_train)

In [51]:
## Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
# Predict class probabilities
label_train_pred = model.predict(tdidf_train_array)

# Compute metrics
acc = accuracy_score(label_train, label_train_pred)
prec = precision_score(label_train, label_train_pred, average='weighted')
rec = recall_score(label_train, label_train_pred, average='weighted')
f1 = f1_score(label_train, label_train_pred, average='weighted')

print(f"Accuracy: {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall: {rec:.4f}")
print(f"F1 Score: {f1:.4f}")

Accuracy: 0.9700
Precision: 0.9702
Recall: 0.9700
F1 Score: 0.9700

In [52]:
label_val_pred = model.predict(tdidf_val_array)
# Compute metrics
acc = accuracy_score(label_val, label_val_pred)
prec = precision_score(label_val, label_val_pred, average='weighted')
rec = recall_score(label_val, label_val_pred, average='weighted')
f1 = f1_score(label_val, label_val_pred, average='weighted')

print(f"Accuracy: {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall: {rec:.4f}")
print(f"F1 Score: {f1:.4f}")

Accuracy: 0.9100
Precision: 0.9274
Recall: 0.9100
F1 Score: 0.9113