# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [ ]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

### Let's divide the training and test set into two partitions

In [ ]:
# Visualize the data
data.head()

# X will have our emails/spam (training data)
X = data['text']

# y will have our classifications (training answers)
y = data['label']

## Data Preprocessing

In [49]:
import numpy as np
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [ ]:
import re

def basic_preprocessing(text):
    # Sub <script> for whitespace
    text = re.sub(r"<script.*?>.*?</script>", " ", text, flags=re.DOTALL | re.IGNORECASE)
    # Sub <style> for whitespace
    text = re.sub(r"<style.*?>.*?</style>", " ", text, flags=re.DOTALL | re.IGNORECASE)
    # Remove remaining '<' '>' characters
    text = re.sub(r"<[^>]+>", " ", text)
    # Remove all special characters
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    # Remove all numbers
    text = re.sub(r"\d", " ", text)
    # Remove single characters
    text = re.sub(r"\b[a-zA-Z]\b", " ", text)
    # Remove single characters from the start
    text = re.sub(r"^(?:[a-zA-Z]\s+)+", " ", text)
    # Sub multiple spaces into a single space
    text = re.sub(r"\s+", " ", text).strip()
    # Remove prefixed 'b'
    text = re.sub(r"^b['\"]", "", text)
    text = re.sub(r"['\"]$", "", text)
    # Convert to lowercase
    text = text.lower()    
    return text

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [ ]:
X_clean = X.apply(basic_preprocessing)

X_clean

## Now let's work on removing stopwords
Remove the stopwords.

In [ ]:
stop_words = stopwords.words("english")

X_clean = [
    " ".join(word for word in doc.split() if word not in stop_words)
    for doc in X_clean
]

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [31]:
lemmatizer = WordNetLemmatizer()

X_lemmatized = [
    " ".join(lemmatizer.lemmatize(word) for word in doc.split())
    for doc in X_clean
]

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [56]:
count_vectorizer = CountVectorizer()

# Convert back to PD Series
X_lemmatized = pd.Series(X_lemmatized, index= y.index)

X_spam = X_lemmatized[y == 1]
X_ham = X_lemmatized[y == 0]

Top 10 Words in Spam messages

In [57]:
X_spam_counts = count_vectorizer.fit_transform(X_spam)

spam_word_counts = pd.DataFrame({
    "word": count_vectorizer.get_feature_names_out(),
    "count": np.asarray(X_spam_counts.sum(axis=0)).ravel()
})

spam_top10 = spam_word_counts.sort_values(
    by="count", ascending=False
).head(10)

spam_top10

              word  count
13794        money    987
229        account    899
2381          bank    801
7881          fund    782
21021  transaction    555
3143      business    514
4445       country    513
13912           mr    490
14285         nbsp    475
13605      million    463

Top 10 Words in Ham messages

In [59]:
X_ham_counts = count_vectorizer.fit_transform(X_ham)

ham_word_counts = pd.DataFrame({
    "word": count_vectorizer.get_feature_names_out(),
    "count": np.asarray(X_ham_counts.sum(axis=0)).ravel()
})

ham_top10 = ham_word_counts.sort_values(
    by="count", ascending=False
).head(10)

ham_top10

           word  count
5416      state    136
4302         pm    127
6463      would    107
4433  president     99
5855       time     95
883        call     94
3688         mr     91
3902      obama     84
4219    percent     81
5058  secretary     79

## Extra features

Splitting the data

In [61]:
from sklearn.model_selection import train_test_split

# Adding previously cleaned data to our original array
data['preprocessed_text'] = X_lemmatized

# Splitting the data into training and validation
data_train, data_val = train_test_split(data, test_size=0.2, random_state=42)

In [62]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,preprocessed_text,money_mark,suspicious_words,text_len
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",1,regard mr nelson smith kindly reply private em...,0,0,79
535,I have not been able to reach oscar this am. W...,0,able reach oscar supposed send pdb receive,0,0,42
695,; Huma Abedin B6I'm checking with Pat on the 5...,0,huma abedin checking pat work jack jake rest a...,0,0,76
557,I can have it announced here on Monday - can't...,0,announced monday today,0,0,22
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,1,bank africaagence san pedro bp san pedro cote ...,1,1,1050

## How would work the Bag of Words with Count Vectorizer concept?

In [68]:
bow_vectorizer = CountVectorizer()

X_bow = bow_vectorizer.fit_transform(data_train['preprocessed_text'])

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [69]:
tfidf_vectorizer = TfidfVectorizer()

X_tfidf = tfidf_vectorizer.fit_transform(data_train['preprocessed_text'])

print(X_tfidf.shape, X_bow.shape)

(800, 28042) (800, 28042)

## And the Train a Classifier?

## Naive Bayes Multinomial

In [72]:
from sklearn.naive_bayes import MultinomialNB

y_train = data_train['label']

nb_model = MultinomialNB()

nb_model.fit(X_tfidf, y_train)

MultinomialNB()

In [73]:
# Validation Data

X_val_tfidf = tfidf_vectorizer.transform(
    data_val['preprocessed_text']
)

y_val = data_val['label']

In [74]:
#Predict and Evaluate

from sklearn.metrics import accuracy_score, classification_report

y_pred = nb_model.predict(X_val_tfidf)

print('Accuracy: ', accuracy_score(y_val, y_pred))
print(classification_report(y_val, y_pred))

Accuracy:  0.935
              precision    recall  f1-score   support

           0       1.00      0.90      0.95       125
           1       0.85      1.00      0.92        75

    accuracy                           0.94       200
   macro avg       0.93      0.95      0.93       200
weighted avg       0.94      0.94      0.94       200

### Naive Bayes fine-tuning

In [78]:
# Define alpha
alphas = [0.01, 0.1, 0.5, 1.0, 2.0, 5.0]

In [80]:
from sklearn.model_selection import GridSearchCV

nb_fine_tune = MultinomialNB()

param_grid = {
    "alpha": [0.01, 0.1, 0.5, 1.0, 2.0, 5.0]
}

grid = GridSearchCV(
    nb_fine_tune,
    param_grid,
    scoring="recall",   # focuses on positive class (spam)
    cv=5
)

grid.fit(X_tfidf, y_train)

GridSearchCV(cv=5, estimator=MultinomialNB(),
             param_grid={'alpha': [0.01, 0.1, 0.5, 1.0, 2.0, 5.0]},
             scoring='recall')

In [81]:
print("Best alpha:", grid.best_params_)
best_nb = grid.best_estimator_

Best alpha: {'alpha': 0.5}

In [ ]:
# Evaluate on Validation Set
y_pred_nb_tuned = best_nb.predict(X_val_tfidf)

print('Accuracy: ', accuracy_score(y_val, y_pred_nb_tuned))
print(classification_report(y_val, y_pred_nb_tuned))

Accuracy:  0.935
              precision    recall  f1-score   support

           0       1.00      0.90      0.95       125
           1       0.85      1.00      0.92        75

    accuracy                           0.94       200
   macro avg       0.93      0.95      0.93       200
weighted avg       0.94      0.94      0.94       200

## Logistic Regression

In [75]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [76]:
# Predict
y_pred_lr = lr.predict(X_val_tfidf)

In [77]:
# Evaluate
print("Accuracy:", accuracy_score(y_val, y_pred_lr))
print(classification_report(y_val, y_pred_lr))

Accuracy: 0.96
              precision    recall  f1-score   support

           0       0.94      1.00      0.97       125
           1       1.00      0.89      0.94        75

    accuracy                           0.96       200
   macro avg       0.97      0.95      0.96       200
weighted avg       0.96      0.96      0.96       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code