In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [9]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 

# Modify for final system
data=data.head(1000)

print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

### Let's divide the training and test set into two partitions

In [11]:
# Your code
from sklearn.model_selection import train_test_split

#Split features (text) and labels (spam/ham)
X= data["text"]
y=data["label"]

#Split into train (80%) and test (20%)
X_train, X_test, y_train, y_test=train_test_split(
    X,y, test_size=0.2, random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (800,)
Test size: (200,)

## Data Preprocessing

In [12]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [13]:
# Your code

import re

def remove_html(text):
    #Remove inline JavaScript/CSS
    text= re.sub(r'<(script|style).*?>.*?</\1>',' ',text, flags=re.DOTALL)

    #Remove HTML comments
    text= re.sub(r'<!--.*?-->',' ', text, flags=re.DOTALL)

    #Remove remaining  HTML tags
    text= re.sub(r'<.*?>',' ' , text)
                 
    return text

#Apply to original text column
data["temp_html_clean"]=data["text"].apply(remove_html)

#Show cleaned preview of first rows
data[["text","temp_html_clean"]].head()

,text,temp_html_clean
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...","DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL..."
1,Will do.,Will do.
2,Nora--Cheryl has emailed dozens of memos about...,Nora--Cheryl has emailed dozens of memos about...
3,Dear Sir=2FMadam=2C I know that this proposal ...,Dear Sir=2FMadam=2C I know that this proposal ...
4,fyi,fyi

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [14]:
# Your code

import re

def clean_remaining(text):
    #Remove special characters
    text= re.sub(r'[^a-zA-Z\s]',' ',text)

    #Remove numbers
    text= re.sub(r'\d+',' ', text)

    #Remove single characters
    text= re.sub(r'\b\w\b',' ' , text)

    #Remove single characters from the start
    text= re.sub(r'^\w\b',' ' , text)

    #Remove multiple spaces by single space
    text= re.sub(r'\s+',' ', text)

    #Remove prefixed b
    text= re.sub("^b'", ' ', text)

    #Convert to lowercase
    text=text.lower()
                 
    return text

#Apply to original text column
data["temp_html_clean"]=data["text"].apply(remove_html)

#Show cleaned preview of first rows
data[["text","temp_html_clean"]].head()

,text,temp_html_clean
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...","DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL..."
1,Will do.,Will do.
2,Nora--Cheryl has emailed dozens of memos about...,Nora--Cheryl has emailed dozens of memos about...
3,Dear Sir=2FMadam=2C I know that this proposal ...,Dear Sir=2FMadam=2C I know that this proposal ...
4,fyi,fyi

## Now let's work on removing stopwords
Remove the stopwords.

In [15]:
# Your code
nltk.download ("stopwords")

stop_words=set(stopwords.words("english"))

def remove_stopwords(text):
    words=text.split()
    words=[word for word in words if word not in stop_words]
    return"".join(words)

data["text_no_stopwords"]= data["temp_html_clean"].apply(remove_stopwords)
data[["temp_html_clean", "text_no_stopwords"]].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\appul\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,temp_html_clean,text_no_stopwords
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...","DEARSIR,STRICTLYAPRIVATEBUSINESSPROPOSALIAMMIK..."
1,Will do.,Willdo.
2,Nora--Cheryl has emailed dozens of memos about...,Nora--CherylemaileddozensmemosHaitiweekend.Can...
3,Dear Sir=2FMadam=2C I know that this proposal ...,DearSir=2FMadam=2CIknowproposalmightsurpriseem...
4,fyi,fyi

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [16]:
# Your code
from nltk.stem import WordNetLemmatizer

nltk.download("wordnet")
lemmatizer=WordNetLemmatizer()

def lemmatize_text(text):
    words=text.split()
    words=[lemmatizer.lemmatize(word) for word in words]
    return" ".join(words)

data["text_lemmatized"]= data["text_no_stopwords"].apply(lemmatize_text)
data[["text_no_stopwords", "text_lemmatized"]].head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\appul\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,text_no_stopwords,text_lemmatized
0,"DEARSIR,STRICTLYAPRIVATEBUSINESSPROPOSALIAMMIK...","DEARSIR,STRICTLYAPRIVATEBUSINESSPROPOSALIAMMIK..."
1,Willdo.,Willdo.
2,Nora--CherylemaileddozensmemosHaitiweekend.Can...,Nora--CherylemaileddozensmemosHaitiweekend.Can...
3,DearSir=2FMadam=2CIknowproposalmightsurpriseem...,DearSir=2FMadam=2CIknowproposalmightsurpriseem...
4,fyi,fyi

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [17]:
# Your code
print(data.columns)

Index(['text', 'label', 'temp_html_clean', 'text_no_stopwords',
       'text_lemmatized'],
      dtype='object')

In [18]:
print(data["label"].unique())

[1 0]

In [19]:
import re
from collections import Counter

def split_joined_words(text):
    #Insert space before any capital letter that follows a lowercase letter
    text= re.sub(r"(?<=[a-z])([A-Z])", r" \1", text)
    #Insert space between alphabetic and numberic tokens
    text= re.sub(r"([a-zA-Z])([0-9])", r"\1\2", text)
    text= re.sub(r"([0-9])([A-Za-z])", r"\1\2", text)
    return text

#Filter texts spam=1 and ham=0
spam_texts=data[data["label"]==1]["text_lemmatized"].apply(split_joined_words)
ham_texts=data[data["label"]==0]["text_lemmatized"].apply(split_joined_words)

# Tokenize and flatten
spam_words=[word for text in spam_texts for word in text.split()]
ham_words=[word for text in ham_texts for word in text.split()]

#Count frequency of words
spam_freq=Counter(spam_words).most_common(10)
ham_freq=Counter(ham_words).most_common(10)

#Print result
print("Top 10 spam words:")
for word, count in spam_freq:
    print(word,":",count)

print("\nTop 10 ham words:")
for word, count in ham_freq:
    print(word,":",count)

Top 10 spam words:
United : 128
South : 111
Dear : 84
States : 84
Bank : 83
IHRo : 72
Million : 69
Hundred : 56
Ghl : 55
Thousand : 52

Top 10 ham words:
Mr : 33
President : 28
State : 26
White : 25
Secretary's : 23
Coll : 22
Degree : 22
United : 21
Cheryl : 20
Men : 20

## Extra features

In [20]:
who

Counter	 HTML	 SnowballStemmer	 TfidfVectorizer	 WordNetLemmatizer	 X	 X_test	 X_train	 clean_remaining
count	 data	 display	 ham_freq	 ham_texts	 ham_words	 lemmatize_text	 lemmatizer	 nltk
pd	 plt	 re	 remove_html	 remove_stopwords	 snowball	 spam_freq	 spam_texts	 spam_words
split_joined_words	 stop_words	 stopwords	 string	 train_test_split	 word	 y	 y_test	 y_train

In [21]:
from sklearn.model_selection import train_test_split

try:
    data_train
except NameError:
    data_train, data_val=train_test_split(data, test_size=0.2, random_state=42)

In [22]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['text_lemmatized'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['text_lemmatized'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['text_lemmatized'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['text_lemmatized'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['text_lemmatized'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['text_lemmatized'].apply(lambda x: len(x)) 

data_train.head()

,text,label,temp_html_clean,text_no_stopwords,text_lemmatized,money_mark,suspicious_words,text_len
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",1,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...","-----------REGARDS,MRNELSONSMITH.KINDLYREPLYME...","-----------REGARDS,MRNELSONSMITH.KINDLYREPLYME...",0,0,95
535,I have not been able to reach oscar this am. W...,0,I have not been able to reach oscar this am. W...,Iablereachoscaram.Wesupposedsendpdb11.Canurece...,Iablereachoscaram.Wesupposedsendpdb11.Canurece...,0,0,52
695,; Huma Abedin B6I'm checking with Pat on the 5...,0,; Huma Abedin B6I'm checking with Pat on the 5...,;HumaAbedinB6I'mcheckingPat50kworkJack&Jakeres...,;HumaAbedinB6I'mcheckingPat50kworkJack&Jakeres...,0,0,74
557,I can have it announced here on Monday - can't...,0,I can have it announced here on Monday - can't...,IannouncedMonday-can'ttoday,IannouncedMonday-can'ttoday,0,0,27
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,1,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,BANKOFAFRICAAGENCESANPEDRO14BP1210SanPedro14Co...,BANKOFAFRICAAGENCESANPEDRO14BP1210SanPedro14Co...,0,1,1134

## How would work the Bag of Words with Count Vectorizer concept?

In [23]:
# Your code
from sklearn.feature_extraction.text import CountVectorizer

vectorizer=CountVectorizer()

#Fitting and transform for training data
X_train_bow= vectorizer.fit_transform(data_train["text_lemmatized"].fillna(""))

#Transform for validation data
X_val_bow= vectorizer.transform(data_val["text_lemmatized"].fillna(""))

#Show result
print("Train Dataset Shape:", X_train_bow.shape)
print("Validation Dataset Shape:", X_val_bow.shape)

Train Dataset Shape: (800, 23899)
Validation Dataset Shape: (200, 23899)

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [24]:
# Your code
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()

#Vectorize all dataset
X_train_tfidf=tfidf.fit_transform(data_train["text_lemmatized"].fillna(""))
X_val_tfidf=tfidf.transform(data_val["text_lemmatized"].fillna(""))

#Print the shape of vectorized dataset
print("Train TF-IDF Shape:", X_train_tfidf)
print("Validation TF-IDF Shape:", X_val_tfidf.shape)

Train TF-IDF Shape: <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 28750 stored elements and shape (800, 23899)>
  Coords	Values
  (0, 17666)	0.3634979139086906
  (0, 15217)	0.49636413794864015
  (0, 13944)	0.49636413794864015
  (0, 15612)	0.49636413794864015
  (0, 23206)	0.27077618990330043
  (0, 8014)	0.23540911036107318
  (1, 11496)	0.5773502691896257
  (1, 22333)	0.5773502691896257
  (1, 7753)	0.5773502691896257
  (2, 11387)	0.5
  (2, 14838)	0.5
  (2, 13571)	0.5
  (2, 6176)	0.5
  (3, 11586)	0.5885006624790431
  (3, 7726)	0.5543770743126513
  (3, 20875)	0.5885006624790431
  (4, 23206)	0.1485675155991478
  (4, 8014)	0.06458128147870056
  (4, 7133)	0.1361707372311381
  (4, 13291)	0.19386812665542455
  (4, 22325)	0.11477720529570729
  (4, 8517)	0.0742837577995739
  (4, 788)	0.1361707372311381
  (4, 6320)	0.1361707372311381
  (4, 18287)	0.1361707372311381
  :	:
  (798, 2368)	0.11901732450341464
  (798, 2848)	0.11901732450341464
  (798, 2420)	0.11901732450341464
  (798, 17770)	0.11901732450341464
  (798, 2227)	0.11901732450341464
  (798, 2570)	0.11901732450341464
  (798, 2028)	0.11901732450341464
  (798, 2573)	0.11901732450341464
  (798, 2618)	0.11901732450341464
  (798, 2889)	0.11901732450341464
  (798, 20709)	0.11901732450341464
  (798, 1729)	0.11901732450341464
  (798, 7853)	0.11901732450341464
  (798, 18397)	0.11901732450341464
  (798, 18519)	0.11901732450341464
  (798, 2043)	0.11901732450341464
  (798, 2579)	0.11901732450341464
  (798, 2591)	0.11901732450341464
  (798, 14670)	0.11901732450341464
  (798, 3258)	0.11901732450341464
  (799, 14304)	0.447213595499958
  (799, 16438)	0.447213595499958
  (799, 11863)	0.447213595499958
  (799, 9687)	0.447213595499958
  (799, 7801)	0.447213595499958
Validation TF-IDF Shape: (200, 23899)

## And the Train a Classifier?

In [25]:
# Your code
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#Train classifier
clf=LogisticRegression(max_iter=300)
clf.fit(X_train_tfidf, data_train["label"])

#Predict on validation set
y_pred=clf.predict(X_val_tfidf)

#Print results
print("Accuracy:", accuracy_score(data_val["label"], y_pred))
print("\nClassification Report:")
print(classification_report(data_val["label"],y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(data_val["label"],y_pred))

Accuracy: 0.93

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.96      0.94       125
           1       0.93      0.88      0.90        75

    accuracy                           0.93       200
   macro avg       0.93      0.92      0.92       200
weighted avg       0.93      0.93      0.93       200


Confusion Matrix:
[[120   5]
 [  9  66]]

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [26]:
for c in extra_cols:
    assert c in data_train.columns and c in data_val.columns, f"Missing column:{c}"

NameError: name 'extra_cols' is not defined

In [111]:
# Your code

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
import pandas as pd

TEXT_COL="text"
LABEL_COL="label"

models=[]

#Define vectorizers
count_vec=CountVectorizer()
tfidf_vec=TfidfVectorizer()

#Extra features already in data_train
extra_cols=["money_mark","suspicious_words","text_len"]

#Bag of words only
models.append((
    "BoW",
    Pipeline([
        ("vec", count_vec),
        ("clf", MultinomialNB())
    ])
))

#TF-ID only
models.append((
    "TF-IDF",
    Pipeline([
        ("vec", tfidf_vec),
        ("clf", MultinomialNB())
        
    ])
))

#BoW with extra features
bow_extra=ColumnTransformer(
    [("bow",count_vec, TEXT_COL),
     ("extra", StandardScaler(with_mean=False), extra_cols)]
)
models.append((
    "BoW + extra",
    Pipeline([
        ("features", bow_extra),
        ("clf", MultinomialNB())
    ])
))

#TF-IDF with extra features
tfidf_extra= ColumnTransformer(
    [("tfidf", tfidf_vec,TEXT_COL),
     ("extra", StandardScaler(with_mean=False), extra_cols)]
)
models.append((
    "TF-IDF + extra",
    Pipeline([
        ("features", tfidf_extra),
        ("clf",MultinomialNB())
    ])
))

results={}

for name, model in models:
    if "extra" in name:
        X_train=data_train[[TEXT_COL]+ extra_cols]
        X_val=data_val[[TEXT_COL]+ extra_cols]
    else:
        X_train=data_train[TEXT_COL].astype(str)
        X_val=data_val[TEXT_COL].astype(str)

    y_train=data_train[LABEL_COL].values
    y_val=data_val[LABEL_COL].values

    model.fit(X_train, y_train)
    preds= model.predict(X_val)

    acc=accuracy_score(y_val, preds)
    results[name]=acc
    print(f"{name}:{acc:4f}")
results

BoW:0.920000
TF-IDF:0.875000
BoW + extra:0.920000
TF-IDF + extra:0.875000

{'BoW': 0.92, 'TF-IDF': 0.875, 'BoW + extra': 0.92, 'TF-IDF + extra': 0.875}